create schema if not exists "game";

create table "game"."accessory" (
    "id" smallint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "game"."accessory" enable row level security;

create table "game"."accessory_translation" (
    "id" smallint generated by default as identity not null,
    "accessory_id" smallint not null,
    "language" character varying not null default 'en'::character varying,
    "name" character varying not null
);


alter table "game"."accessory_translation" enable row level security;

create table "game"."action_card" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "game"."action_card" enable row level security;

create table "game"."action_card_settings" (
    "id" integer generated by default as identity not null,
    "game_id" integer not null,
    "state_id" smallint not null,
    "card_limit" smallint,
    "card_seconds" smallint,
    "is_auto_next" boolean not null default false,
    "is_player_creative" boolean not null default false,
    "has_buzzer" boolean not null default false,
    "created_at" timestamp with time zone not null default now(),
    "allow_sentence" boolean not null default true,
    "can_repeat" boolean not null default false,
    "card_based_timer" boolean not null default false,
    "exclude_players_amount" character varying,
    "one_card_per_player" boolean not null default false
);


alter table "game"."action_card_settings" enable row level security;

create table "game"."action_card_settings_has_action_card" (
    "action_card_settings_id" integer not null,
    "action_card_id" bigint not null
);


alter table "game"."action_card_settings_has_action_card" enable row level security;

create table "game"."action_card_settings_translation" (
    "id" integer generated by default as identity not null,
    "action_card_settings_id" integer not null,
    "language" character varying not null default 'en'::character varying,
    "prompt" text,
    "player_creative_prompt" text
);


alter table "game"."action_card_settings_translation" enable row level security;

create table "game"."action_card_state" (
    "id" smallint generated by default as identity not null,
    "name" character varying not null
);


alter table "game"."action_card_state" enable row level security;

create table "game"."action_card_translation" (
    "id" bigint generated by default as identity not null,
    "action_card_id" bigint not null,
    "language" character varying not null default 'en'::character varying,
    "value" text not null
);


alter table "game"."action_card_translation" enable row level security;

create table "game"."challenge" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "message" text not null
);


alter table "game"."challenge" enable row level security;

create table "game"."game" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "min_players" smallint not null default '2'::smallint,
    "max_players" smallint,
    "activity_level" smallint not null default '0'::smallint,
    "minutes" smallint not null default '1'::smallint,
    "game_category_id" smallint not null,
    "game_audience_id" smallint,
    "drunk_level" smallint not null default '0'::smallint,
    "game_end_type" text not null default 'finish'::text,
    "name" character varying not null,
    "deleted_at" timestamp with time zone,
    "has_winner" boolean not null default false,
    "active" boolean not null default false,
    "custom_rules_image" character varying
);


alter table "game"."game" enable row level security;

create table "game"."game_audience" (
    "id" smallint generated by default as identity not null,
    "name" character varying not null
);


alter table "game"."game_audience" enable row level security;

create table "game"."game_category" (
    "id" smallint generated by default as identity not null,
    "name" character varying not null
);


alter table "game"."game_category" enable row level security;

create table "game"."game_has_accessory" (
    "id" integer generated by default as identity not null,
    "game_id" integer not null,
    "accessory_id" smallint not null
);


alter table "game"."game_has_accessory" enable row level security;

create table "game"."game_has_game_type" (
    "id" integer generated by default as identity not null,
    "game_id" integer not null,
    "game_type_id" smallint not null
);


alter table "game"."game_has_game_type" enable row level security;

create table "game"."game_translation" (
    "id" integer generated by default as identity not null,
    "game_id" integer not null,
    "language" character varying not null default 'en'::character varying,
    "name" character varying not null,
    "custom_end_game_sentence" text,
    "has_winner_prompt" text,
    "descriptions" jsonb not null default '{}'::jsonb
);


alter table "game"."game_translation" enable row level security;

create table "game"."game_type" (
    "id" smallint generated by default as identity not null,
    "name" character varying not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "game"."game_type" enable row level security;

CREATE UNIQUE INDEX accessory_pkey ON game.accessory USING btree (id);

CREATE UNIQUE INDEX accessory_translation_pkey ON game.accessory_translation USING btree (id);

CREATE UNIQUE INDEX action_card_pkey ON game.action_card USING btree (id);

CREATE UNIQUE INDEX action_card_settings_has_action_card_pkey ON game.action_card_settings_has_action_card USING btree (action_card_settings_id, action_card_id);

CREATE UNIQUE INDEX action_card_settings_pkey ON game.action_card_settings USING btree (id);

CREATE UNIQUE INDEX action_card_settings_translation_pkey ON game.action_card_settings_translation USING btree (id);

CREATE UNIQUE INDEX action_card_state_name_key ON game.action_card_state USING btree (name);

CREATE UNIQUE INDEX action_card_state_pkey ON game.action_card_state USING btree (id);

CREATE UNIQUE INDEX action_card_translation_pkey ON game.action_card_translation USING btree (id);

CREATE UNIQUE INDEX challenge_pkey ON game.challenge USING btree (id);

CREATE UNIQUE INDEX game_accessory_unique ON game.game_has_accessory USING btree (game_id, accessory_id);

CREATE UNIQUE INDEX game_audience_type_name_key ON game.game_audience USING btree (name);

CREATE UNIQUE INDEX game_audience_type_pkey ON game.game_audience USING btree (id);

CREATE UNIQUE INDEX game_category_name_key ON game.game_category USING btree (name);

CREATE UNIQUE INDEX game_category_pkey ON game.game_category USING btree (id);

CREATE UNIQUE INDEX game_has_accessory_pkey ON game.game_has_accessory USING btree (id);

CREATE UNIQUE INDEX game_has_game_type_pkey ON game.game_has_game_type USING btree (id);

CREATE UNIQUE INDEX game_has_game_type_unique ON game.game_has_game_type USING btree (game_id, game_type_id);

CREATE UNIQUE INDEX game_name_key ON game.game USING btree (name);

CREATE UNIQUE INDEX game_pkey ON game.game USING btree (id);

CREATE UNIQUE INDEX game_translation_pkey ON game.game_translation USING btree (id);

CREATE UNIQUE INDEX game_type_name_unique ON game.game_type USING btree (name);

CREATE UNIQUE INDEX game_type_pkey ON game.game_type USING btree (id);

alter table "game"."accessory" add constraint "accessory_pkey" PRIMARY KEY using index "accessory_pkey";

alter table "game"."accessory_translation" add constraint "accessory_translation_pkey" PRIMARY KEY using index "accessory_translation_pkey";

alter table "game"."action_card" add constraint "action_card_pkey" PRIMARY KEY using index "action_card_pkey";

alter table "game"."action_card_settings" add constraint "action_card_settings_pkey" PRIMARY KEY using index "action_card_settings_pkey";

alter table "game"."action_card_settings_has_action_card" add constraint "action_card_settings_has_action_card_pkey" PRIMARY KEY using index "action_card_settings_has_action_card_pkey";

alter table "game"."action_card_settings_translation" add constraint "action_card_settings_translation_pkey" PRIMARY KEY using index "action_card_settings_translation_pkey";

alter table "game"."action_card_state" add constraint "action_card_state_pkey" PRIMARY KEY using index "action_card_state_pkey";

alter table "game"."action_card_translation" add constraint "action_card_translation_pkey" PRIMARY KEY using index "action_card_translation_pkey";

alter table "game"."challenge" add constraint "challenge_pkey" PRIMARY KEY using index "challenge_pkey";

alter table "game"."game" add constraint "game_pkey" PRIMARY KEY using index "game_pkey";

alter table "game"."game_audience" add constraint "game_audience_type_pkey" PRIMARY KEY using index "game_audience_type_pkey";

alter table "game"."game_category" add constraint "game_category_pkey" PRIMARY KEY using index "game_category_pkey";

alter table "game"."game_has_accessory" add constraint "game_has_accessory_pkey" PRIMARY KEY using index "game_has_accessory_pkey";

alter table "game"."game_has_game_type" add constraint "game_has_game_type_pkey" PRIMARY KEY using index "game_has_game_type_pkey";

alter table "game"."game_translation" add constraint "game_translation_pkey" PRIMARY KEY using index "game_translation_pkey";

alter table "game"."game_type" add constraint "game_type_pkey" PRIMARY KEY using index "game_type_pkey";

alter table "game"."accessory_translation" add constraint "game_accessory_translation_accessory_id_fkey" FOREIGN KEY (accessory_id) REFERENCES game.accessory(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "game"."accessory_translation" validate constraint "game_accessory_translation_accessory_id_fkey";

alter table "game"."action_card_settings" add constraint "game_action_card_settings_game_id_fkey" FOREIGN KEY (game_id) REFERENCES game.game(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "game"."action_card_settings" validate constraint "game_action_card_settings_game_id_fkey";

alter table "game"."action_card_settings" add constraint "game_action_card_settings_state_id_fkey" FOREIGN KEY (state_id) REFERENCES game.action_card_state(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "game"."action_card_settings" validate constraint "game_action_card_settings_state_id_fkey";

alter table "game"."action_card_settings_has_action_card" add constraint "game_action_card_settings_has_action_card_action_card_id_fkey" FOREIGN KEY (action_card_id) REFERENCES game.action_card(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "game"."action_card_settings_has_action_card" validate constraint "game_action_card_settings_has_action_card_action_card_id_fkey";

alter table "game"."action_card_settings_has_action_card" add constraint "game_action_card_settings_has_action_card_action_card_setting" FOREIGN KEY (action_card_settings_id) REFERENCES game.action_card_settings(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "game"."action_card_settings_has_action_card" validate constraint "game_action_card_settings_has_action_card_action_card_setting";

alter table "game"."action_card_settings_translation" add constraint "game_action_card_settings_translation_action_card_settings_id" FOREIGN KEY (action_card_settings_id) REFERENCES game.action_card_settings(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "game"."action_card_settings_translation" validate constraint "game_action_card_settings_translation_action_card_settings_id";

alter table "game"."action_card_state" add constraint "action_card_state_name_key" UNIQUE using index "action_card_state_name_key";

alter table "game"."action_card_translation" add constraint "game_action_card_translation_action_card_id_fkey" FOREIGN KEY (action_card_id) REFERENCES game.action_card(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "game"."action_card_translation" validate constraint "game_action_card_translation_action_card_id_fkey";

alter table "game"."game" add constraint "game_game_game_audience_id_fkey" FOREIGN KEY (game_audience_id) REFERENCES game.game_audience(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "game"."game" validate constraint "game_game_game_audience_id_fkey";

alter table "game"."game" add constraint "game_game_game_category_id_fkey" FOREIGN KEY (game_category_id) REFERENCES game.game_category(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "game"."game" validate constraint "game_game_game_category_id_fkey";

alter table "game"."game" add constraint "game_name_key" UNIQUE using index "game_name_key";

alter table "game"."game_audience" add constraint "game_audience_type_name_key" UNIQUE using index "game_audience_type_name_key";

alter table "game"."game_category" add constraint "game_category_name_key" UNIQUE using index "game_category_name_key";

alter table "game"."game_has_accessory" add constraint "game_accessory_unique" UNIQUE using index "game_accessory_unique";

alter table "game"."game_has_accessory" add constraint "game_game_has_accessory_accessory_id_fkey" FOREIGN KEY (accessory_id) REFERENCES game.accessory(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "game"."game_has_accessory" validate constraint "game_game_has_accessory_accessory_id_fkey";

alter table "game"."game_has_accessory" add constraint "game_game_has_accessory_game_id_fkey" FOREIGN KEY (game_id) REFERENCES game.game(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "game"."game_has_accessory" validate constraint "game_game_has_accessory_game_id_fkey";

alter table "game"."game_has_game_type" add constraint "game_game_has_game_type_game_id_fkey" FOREIGN KEY (game_id) REFERENCES game.game(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "game"."game_has_game_type" validate constraint "game_game_has_game_type_game_id_fkey";

alter table "game"."game_has_game_type" add constraint "game_game_has_game_type_game_type_id_fkey" FOREIGN KEY (game_type_id) REFERENCES game.game_type(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "game"."game_has_game_type" validate constraint "game_game_has_game_type_game_type_id_fkey";

alter table "game"."game_has_game_type" add constraint "game_has_game_type_unique" UNIQUE using index "game_has_game_type_unique";

alter table "game"."game_translation" add constraint "game_game_translation_game_id_fkey" FOREIGN KEY (game_id) REFERENCES game.game(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "game"."game_translation" validate constraint "game_game_translation_game_id_fkey";

alter table "game"."game_type" add constraint "game_type_name_unique" UNIQUE using index "game_type_name_unique";

grant delete on table "game"."accessory" to "anon";

grant insert on table "game"."accessory" to "anon";

grant references on table "game"."accessory" to "anon";

grant select on table "game"."accessory" to "anon";

grant trigger on table "game"."accessory" to "anon";

grant truncate on table "game"."accessory" to "anon";

grant update on table "game"."accessory" to "anon";

grant delete on table "game"."accessory" to "authenticated";

grant insert on table "game"."accessory" to "authenticated";

grant references on table "game"."accessory" to "authenticated";

grant select on table "game"."accessory" to "authenticated";

grant trigger on table "game"."accessory" to "authenticated";

grant truncate on table "game"."accessory" to "authenticated";

grant update on table "game"."accessory" to "authenticated";

grant delete on table "game"."accessory" to "service_role";

grant insert on table "game"."accessory" to "service_role";

grant references on table "game"."accessory" to "service_role";

grant select on table "game"."accessory" to "service_role";

grant trigger on table "game"."accessory" to "service_role";

grant truncate on table "game"."accessory" to "service_role";

grant update on table "game"."accessory" to "service_role";

grant delete on table "game"."accessory_translation" to "anon";

grant insert on table "game"."accessory_translation" to "anon";

grant references on table "game"."accessory_translation" to "anon";

grant select on table "game"."accessory_translation" to "anon";

grant trigger on table "game"."accessory_translation" to "anon";

grant truncate on table "game"."accessory_translation" to "anon";

grant update on table "game"."accessory_translation" to "anon";

grant delete on table "game"."accessory_translation" to "authenticated";

grant insert on table "game"."accessory_translation" to "authenticated";

grant references on table "game"."accessory_translation" to "authenticated";

grant select on table "game"."accessory_translation" to "authenticated";

grant trigger on table "game"."accessory_translation" to "authenticated";

grant truncate on table "game"."accessory_translation" to "authenticated";

grant update on table "game"."accessory_translation" to "authenticated";

grant delete on table "game"."accessory_translation" to "service_role";

grant insert on table "game"."accessory_translation" to "service_role";

grant references on table "game"."accessory_translation" to "service_role";

grant select on table "game"."accessory_translation" to "service_role";

grant trigger on table "game"."accessory_translation" to "service_role";

grant truncate on table "game"."accessory_translation" to "service_role";

grant update on table "game"."accessory_translation" to "service_role";

grant delete on table "game"."action_card" to "anon";

grant insert on table "game"."action_card" to "anon";

grant references on table "game"."action_card" to "anon";

grant select on table "game"."action_card" to "anon";

grant trigger on table "game"."action_card" to "anon";

grant truncate on table "game"."action_card" to "anon";

grant update on table "game"."action_card" to "anon";

grant delete on table "game"."action_card" to "authenticated";

grant insert on table "game"."action_card" to "authenticated";

grant references on table "game"."action_card" to "authenticated";

grant select on table "game"."action_card" to "authenticated";

grant trigger on table "game"."action_card" to "authenticated";

grant truncate on table "game"."action_card" to "authenticated";

grant update on table "game"."action_card" to "authenticated";

grant delete on table "game"."action_card" to "service_role";

grant insert on table "game"."action_card" to "service_role";

grant references on table "game"."action_card" to "service_role";

grant select on table "game"."action_card" to "service_role";

grant trigger on table "game"."action_card" to "service_role";

grant truncate on table "game"."action_card" to "service_role";

grant update on table "game"."action_card" to "service_role";

grant delete on table "game"."action_card_settings" to "anon";

grant insert on table "game"."action_card_settings" to "anon";

grant references on table "game"."action_card_settings" to "anon";

grant select on table "game"."action_card_settings" to "anon";

grant trigger on table "game"."action_card_settings" to "anon";

grant truncate on table "game"."action_card_settings" to "anon";

grant update on table "game"."action_card_settings" to "anon";

grant delete on table "game"."action_card_settings" to "authenticated";

grant insert on table "game"."action_card_settings" to "authenticated";

grant references on table "game"."action_card_settings" to "authenticated";

grant select on table "game"."action_card_settings" to "authenticated";

grant trigger on table "game"."action_card_settings" to "authenticated";

grant truncate on table "game"."action_card_settings" to "authenticated";

grant update on table "game"."action_card_settings" to "authenticated";

grant delete on table "game"."action_card_settings" to "service_role";

grant insert on table "game"."action_card_settings" to "service_role";

grant references on table "game"."action_card_settings" to "service_role";

grant select on table "game"."action_card_settings" to "service_role";

grant trigger on table "game"."action_card_settings" to "service_role";

grant truncate on table "game"."action_card_settings" to "service_role";

grant update on table "game"."action_card_settings" to "service_role";

grant delete on table "game"."action_card_settings_has_action_card" to "anon";

grant insert on table "game"."action_card_settings_has_action_card" to "anon";

grant references on table "game"."action_card_settings_has_action_card" to "anon";

grant select on table "game"."action_card_settings_has_action_card" to "anon";

grant trigger on table "game"."action_card_settings_has_action_card" to "anon";

grant truncate on table "game"."action_card_settings_has_action_card" to "anon";

grant update on table "game"."action_card_settings_has_action_card" to "anon";

grant delete on table "game"."action_card_settings_has_action_card" to "authenticated";

grant insert on table "game"."action_card_settings_has_action_card" to "authenticated";

grant references on table "game"."action_card_settings_has_action_card" to "authenticated";

grant select on table "game"."action_card_settings_has_action_card" to "authenticated";

grant trigger on table "game"."action_card_settings_has_action_card" to "authenticated";

grant truncate on table "game"."action_card_settings_has_action_card" to "authenticated";

grant update on table "game"."action_card_settings_has_action_card" to "authenticated";

grant delete on table "game"."action_card_settings_has_action_card" to "service_role";

grant insert on table "game"."action_card_settings_has_action_card" to "service_role";

grant references on table "game"."action_card_settings_has_action_card" to "service_role";

grant select on table "game"."action_card_settings_has_action_card" to "service_role";

grant trigger on table "game"."action_card_settings_has_action_card" to "service_role";

grant truncate on table "game"."action_card_settings_has_action_card" to "service_role";

grant update on table "game"."action_card_settings_has_action_card" to "service_role";

grant delete on table "game"."action_card_settings_translation" to "anon";

grant insert on table "game"."action_card_settings_translation" to "anon";

grant references on table "game"."action_card_settings_translation" to "anon";

grant select on table "game"."action_card_settings_translation" to "anon";

grant trigger on table "game"."action_card_settings_translation" to "anon";

grant truncate on table "game"."action_card_settings_translation" to "anon";

grant update on table "game"."action_card_settings_translation" to "anon";

grant delete on table "game"."action_card_settings_translation" to "authenticated";

grant insert on table "game"."action_card_settings_translation" to "authenticated";

grant references on table "game"."action_card_settings_translation" to "authenticated";

grant select on table "game"."action_card_settings_translation" to "authenticated";

grant trigger on table "game"."action_card_settings_translation" to "authenticated";

grant truncate on table "game"."action_card_settings_translation" to "authenticated";

grant update on table "game"."action_card_settings_translation" to "authenticated";

grant delete on table "game"."action_card_settings_translation" to "service_role";

grant insert on table "game"."action_card_settings_translation" to "service_role";

grant references on table "game"."action_card_settings_translation" to "service_role";

grant select on table "game"."action_card_settings_translation" to "service_role";

grant trigger on table "game"."action_card_settings_translation" to "service_role";

grant truncate on table "game"."action_card_settings_translation" to "service_role";

grant update on table "game"."action_card_settings_translation" to "service_role";

grant delete on table "game"."action_card_state" to "anon";

grant insert on table "game"."action_card_state" to "anon";

grant references on table "game"."action_card_state" to "anon";

grant select on table "game"."action_card_state" to "anon";

grant trigger on table "game"."action_card_state" to "anon";

grant truncate on table "game"."action_card_state" to "anon";

grant update on table "game"."action_card_state" to "anon";

grant delete on table "game"."action_card_state" to "authenticated";

grant insert on table "game"."action_card_state" to "authenticated";

grant references on table "game"."action_card_state" to "authenticated";

grant select on table "game"."action_card_state" to "authenticated";

grant trigger on table "game"."action_card_state" to "authenticated";

grant truncate on table "game"."action_card_state" to "authenticated";

grant update on table "game"."action_card_state" to "authenticated";

grant delete on table "game"."action_card_state" to "service_role";

grant insert on table "game"."action_card_state" to "service_role";

grant references on table "game"."action_card_state" to "service_role";

grant select on table "game"."action_card_state" to "service_role";

grant trigger on table "game"."action_card_state" to "service_role";

grant truncate on table "game"."action_card_state" to "service_role";

grant update on table "game"."action_card_state" to "service_role";

grant delete on table "game"."action_card_translation" to "anon";

grant insert on table "game"."action_card_translation" to "anon";

grant references on table "game"."action_card_translation" to "anon";

grant select on table "game"."action_card_translation" to "anon";

grant trigger on table "game"."action_card_translation" to "anon";

grant truncate on table "game"."action_card_translation" to "anon";

grant update on table "game"."action_card_translation" to "anon";

grant delete on table "game"."action_card_translation" to "authenticated";

grant insert on table "game"."action_card_translation" to "authenticated";

grant references on table "game"."action_card_translation" to "authenticated";

grant select on table "game"."action_card_translation" to "authenticated";

grant trigger on table "game"."action_card_translation" to "authenticated";

grant truncate on table "game"."action_card_translation" to "authenticated";

grant update on table "game"."action_card_translation" to "authenticated";

grant delete on table "game"."action_card_translation" to "service_role";

grant insert on table "game"."action_card_translation" to "service_role";

grant references on table "game"."action_card_translation" to "service_role";

grant select on table "game"."action_card_translation" to "service_role";

grant trigger on table "game"."action_card_translation" to "service_role";

grant truncate on table "game"."action_card_translation" to "service_role";

grant update on table "game"."action_card_translation" to "service_role";

grant delete on table "game"."challenge" to "anon";

grant insert on table "game"."challenge" to "anon";

grant references on table "game"."challenge" to "anon";

grant select on table "game"."challenge" to "anon";

grant trigger on table "game"."challenge" to "anon";

grant truncate on table "game"."challenge" to "anon";

grant update on table "game"."challenge" to "anon";

grant delete on table "game"."challenge" to "authenticated";

grant insert on table "game"."challenge" to "authenticated";

grant references on table "game"."challenge" to "authenticated";

grant select on table "game"."challenge" to "authenticated";

grant trigger on table "game"."challenge" to "authenticated";

grant truncate on table "game"."challenge" to "authenticated";

grant update on table "game"."challenge" to "authenticated";

grant delete on table "game"."challenge" to "service_role";

grant insert on table "game"."challenge" to "service_role";

grant references on table "game"."challenge" to "service_role";

grant select on table "game"."challenge" to "service_role";

grant trigger on table "game"."challenge" to "service_role";

grant truncate on table "game"."challenge" to "service_role";

grant update on table "game"."challenge" to "service_role";

grant delete on table "game"."game" to "anon";

grant insert on table "game"."game" to "anon";

grant references on table "game"."game" to "anon";

grant select on table "game"."game" to "anon";

grant trigger on table "game"."game" to "anon";

grant truncate on table "game"."game" to "anon";

grant update on table "game"."game" to "anon";

grant delete on table "game"."game" to "authenticated";

grant insert on table "game"."game" to "authenticated";

grant references on table "game"."game" to "authenticated";

grant select on table "game"."game" to "authenticated";

grant trigger on table "game"."game" to "authenticated";

grant truncate on table "game"."game" to "authenticated";

grant update on table "game"."game" to "authenticated";

grant delete on table "game"."game" to "service_role";

grant insert on table "game"."game" to "service_role";

grant references on table "game"."game" to "service_role";

grant select on table "game"."game" to "service_role";

grant trigger on table "game"."game" to "service_role";

grant truncate on table "game"."game" to "service_role";

grant update on table "game"."game" to "service_role";

grant delete on table "game"."game_audience" to "anon";

grant insert on table "game"."game_audience" to "anon";

grant references on table "game"."game_audience" to "anon";

grant select on table "game"."game_audience" to "anon";

grant trigger on table "game"."game_audience" to "anon";

grant truncate on table "game"."game_audience" to "anon";

grant update on table "game"."game_audience" to "anon";

grant delete on table "game"."game_audience" to "authenticated";

grant insert on table "game"."game_audience" to "authenticated";

grant references on table "game"."game_audience" to "authenticated";

grant select on table "game"."game_audience" to "authenticated";

grant trigger on table "game"."game_audience" to "authenticated";

grant truncate on table "game"."game_audience" to "authenticated";

grant update on table "game"."game_audience" to "authenticated";

grant delete on table "game"."game_audience" to "service_role";

grant insert on table "game"."game_audience" to "service_role";

grant references on table "game"."game_audience" to "service_role";

grant select on table "game"."game_audience" to "service_role";

grant trigger on table "game"."game_audience" to "service_role";

grant truncate on table "game"."game_audience" to "service_role";

grant update on table "game"."game_audience" to "service_role";

grant delete on table "game"."game_category" to "anon";

grant insert on table "game"."game_category" to "anon";

grant references on table "game"."game_category" to "anon";

grant select on table "game"."game_category" to "anon";

grant trigger on table "game"."game_category" to "anon";

grant truncate on table "game"."game_category" to "anon";

grant update on table "game"."game_category" to "anon";

grant delete on table "game"."game_category" to "authenticated";

grant insert on table "game"."game_category" to "authenticated";

grant references on table "game"."game_category" to "authenticated";

grant select on table "game"."game_category" to "authenticated";

grant trigger on table "game"."game_category" to "authenticated";

grant truncate on table "game"."game_category" to "authenticated";

grant update on table "game"."game_category" to "authenticated";

grant delete on table "game"."game_category" to "service_role";

grant insert on table "game"."game_category" to "service_role";

grant references on table "game"."game_category" to "service_role";

grant select on table "game"."game_category" to "service_role";

grant trigger on table "game"."game_category" to "service_role";

grant truncate on table "game"."game_category" to "service_role";

grant update on table "game"."game_category" to "service_role";

grant delete on table "game"."game_has_accessory" to "anon";

grant insert on table "game"."game_has_accessory" to "anon";

grant references on table "game"."game_has_accessory" to "anon";

grant select on table "game"."game_has_accessory" to "anon";

grant trigger on table "game"."game_has_accessory" to "anon";

grant truncate on table "game"."game_has_accessory" to "anon";

grant update on table "game"."game_has_accessory" to "anon";

grant delete on table "game"."game_has_accessory" to "authenticated";

grant insert on table "game"."game_has_accessory" to "authenticated";

grant references on table "game"."game_has_accessory" to "authenticated";

grant select on table "game"."game_has_accessory" to "authenticated";

grant trigger on table "game"."game_has_accessory" to "authenticated";

grant truncate on table "game"."game_has_accessory" to "authenticated";

grant update on table "game"."game_has_accessory" to "authenticated";

grant delete on table "game"."game_has_accessory" to "service_role";

grant insert on table "game"."game_has_accessory" to "service_role";

grant references on table "game"."game_has_accessory" to "service_role";

grant select on table "game"."game_has_accessory" to "service_role";

grant trigger on table "game"."game_has_accessory" to "service_role";

grant truncate on table "game"."game_has_accessory" to "service_role";

grant update on table "game"."game_has_accessory" to "service_role";

grant delete on table "game"."game_has_game_type" to "anon";

grant insert on table "game"."game_has_game_type" to "anon";

grant references on table "game"."game_has_game_type" to "anon";

grant select on table "game"."game_has_game_type" to "anon";

grant trigger on table "game"."game_has_game_type" to "anon";

grant truncate on table "game"."game_has_game_type" to "anon";

grant update on table "game"."game_has_game_type" to "anon";

grant delete on table "game"."game_has_game_type" to "authenticated";

grant insert on table "game"."game_has_game_type" to "authenticated";

grant references on table "game"."game_has_game_type" to "authenticated";

grant select on table "game"."game_has_game_type" to "authenticated";

grant trigger on table "game"."game_has_game_type" to "authenticated";

grant truncate on table "game"."game_has_game_type" to "authenticated";

grant update on table "game"."game_has_game_type" to "authenticated";

grant delete on table "game"."game_has_game_type" to "service_role";

grant insert on table "game"."game_has_game_type" to "service_role";

grant references on table "game"."game_has_game_type" to "service_role";

grant select on table "game"."game_has_game_type" to "service_role";

grant trigger on table "game"."game_has_game_type" to "service_role";

grant truncate on table "game"."game_has_game_type" to "service_role";

grant update on table "game"."game_has_game_type" to "service_role";

grant delete on table "game"."game_translation" to "anon";

grant insert on table "game"."game_translation" to "anon";

grant references on table "game"."game_translation" to "anon";

grant select on table "game"."game_translation" to "anon";

grant trigger on table "game"."game_translation" to "anon";

grant truncate on table "game"."game_translation" to "anon";

grant update on table "game"."game_translation" to "anon";

grant delete on table "game"."game_translation" to "authenticated";

grant insert on table "game"."game_translation" to "authenticated";

grant references on table "game"."game_translation" to "authenticated";

grant select on table "game"."game_translation" to "authenticated";

grant trigger on table "game"."game_translation" to "authenticated";

grant truncate on table "game"."game_translation" to "authenticated";

grant update on table "game"."game_translation" to "authenticated";

grant delete on table "game"."game_translation" to "service_role";

grant insert on table "game"."game_translation" to "service_role";

grant references on table "game"."game_translation" to "service_role";

grant select on table "game"."game_translation" to "service_role";

grant trigger on table "game"."game_translation" to "service_role";

grant truncate on table "game"."game_translation" to "service_role";

grant update on table "game"."game_translation" to "service_role";

grant delete on table "game"."game_type" to "anon";

grant insert on table "game"."game_type" to "anon";

grant references on table "game"."game_type" to "anon";

grant select on table "game"."game_type" to "anon";

grant trigger on table "game"."game_type" to "anon";

grant truncate on table "game"."game_type" to "anon";

grant update on table "game"."game_type" to "anon";

grant delete on table "game"."game_type" to "authenticated";

grant insert on table "game"."game_type" to "authenticated";

grant references on table "game"."game_type" to "authenticated";

grant select on table "game"."game_type" to "authenticated";

grant trigger on table "game"."game_type" to "authenticated";

grant truncate on table "game"."game_type" to "authenticated";

grant update on table "game"."game_type" to "authenticated";

grant delete on table "game"."game_type" to "service_role";

grant insert on table "game"."game_type" to "service_role";

grant references on table "game"."game_type" to "service_role";

grant select on table "game"."game_type" to "service_role";

grant trigger on table "game"."game_type" to "service_role";

grant truncate on table "game"."game_type" to "service_role";

grant update on table "game"."game_type" to "service_role";

create policy "Enable delete for authenticated users only"
on "game"."accessory"
as permissive
for delete
to authenticated
using (true);


create policy "Enable insert for authenticated users only"
on "game"."accessory"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "game"."accessory"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "game"."accessory_translation"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "game"."accessory_translation"
as permissive
for select
to public
using (true);


create policy "Enable delete for authenticated users only"
on "game"."action_card"
as permissive
for delete
to authenticated
using (true);


create policy "Enable insert for authenticated users only"
on "game"."action_card"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "game"."action_card"
as permissive
for select
to public
using (true);


create policy "Enable update for authenticated users only"
on "game"."action_card"
as permissive
for update
to authenticated
using (true)
with check (true);


create policy "Enable insert for authenticated users only"
on "game"."action_card_settings"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "game"."action_card_settings"
as permissive
for select
to public
using (true);


create policy "Enable update for authenticated users only"
on "game"."action_card_settings"
as permissive
for update
to authenticated
using (true)
with check (true);


create policy "Enable insert for authenticated users only"
on "game"."action_card_settings_has_action_card"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "game"."action_card_settings_has_action_card"
as permissive
for select
to public
using (true);


create policy "Enable update for authenticated users only"
on "game"."action_card_settings_has_action_card"
as permissive
for update
to authenticated
using (true)
with check (true);


create policy "Enable insert for authenticated users only"
on "game"."action_card_settings_translation"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "game"."action_card_settings_translation"
as permissive
for select
to public
using (true);


create policy "Enable update for authenticated users only"
on "game"."action_card_settings_translation"
as permissive
for update
to authenticated
using (true)
with check (true);


create policy "Enable read access for all users"
on "game"."action_card_state"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "game"."action_card_translation"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "game"."action_card_translation"
as permissive
for select
to public
using (true);


create policy "Enable update for authenticated users only"
on "game"."action_card_translation"
as permissive
for update
to authenticated
using (true)
with check (true);


create policy "Enable read access for all users"
on "game"."challenge"
as permissive
for select
to public
using (true);


create policy "Enable delete for authenticated users only"
on "game"."game"
as permissive
for delete
to authenticated
using (true);


create policy "Enable insert for authenticated users only"
on "game"."game"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "game"."game"
as permissive
for select
to public
using (true);


create policy "Enable update for authenticated users only"
on "game"."game"
as permissive
for update
to authenticated
using (true)
with check (true);


create policy "Enable read access for all users"
on "game"."game_audience"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "game"."game_category"
as permissive
for select
to public
using (true);


create policy "Enable delete for authenticated users only"
on "game"."game_has_accessory"
as permissive
for delete
to authenticated
using (true);


create policy "Enable insert for authenticated users only"
on "game"."game_has_accessory"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "game"."game_has_accessory"
as permissive
for select
to public
using (true);


create policy "Enable delete for authenticated users only"
on "game"."game_has_game_type"
as permissive
for delete
to authenticated
using (true);


create policy "Enable insert for authenticated users only"
on "game"."game_has_game_type"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "game"."game_has_game_type"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "game"."game_translation"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "game"."game_translation"
as permissive
for select
to public
using (true);


create policy "Enable update for authenticated users only"
on "game"."game_translation"
as permissive
for update
to authenticated
using (true)
with check (true);


create policy "Enable read access for all users"
on "game"."game_type"
as permissive
for select
to public
using (true);



create schema if not exists "notification";

create table "notification"."alert" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "target_version" character varying not null,
    "button_url" text
);


alter table "notification"."alert" enable row level security;

create table "notification"."alert_translation" (
    "id" bigint generated by default as identity not null,
    "alert_id" integer not null,
    "language" character varying not null default 'en'::character varying,
    "title" text not null,
    "description" text not null,
    "button_title" character varying
);


alter table "notification"."alert_translation" enable row level security;

create table "notification"."app_version" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "value" character varying not null
);


alter table "notification"."app_version" enable row level security;

CREATE UNIQUE INDEX alert_pkey ON notification.alert USING btree (id);

CREATE UNIQUE INDEX alert_translation_pkey ON notification.alert_translation USING btree (id);

CREATE UNIQUE INDEX app_version_pkey ON notification.app_version USING btree (id);

CREATE UNIQUE INDEX app_version_value_key ON notification.app_version USING btree (value);

alter table "notification"."alert" add constraint "alert_pkey" PRIMARY KEY using index "alert_pkey";

alter table "notification"."alert_translation" add constraint "alert_translation_pkey" PRIMARY KEY using index "alert_translation_pkey";

alter table "notification"."app_version" add constraint "app_version_pkey" PRIMARY KEY using index "app_version_pkey";

alter table "notification"."alert_translation" add constraint "alert_translation_alert_id_fkey" FOREIGN KEY (alert_id) REFERENCES notification.alert(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "notification"."alert_translation" validate constraint "alert_translation_alert_id_fkey";

alter table "notification"."app_version" add constraint "app_version_value_key" UNIQUE using index "app_version_value_key";

grant delete on table "notification"."alert" to "anon";

grant insert on table "notification"."alert" to "anon";

grant references on table "notification"."alert" to "anon";

grant select on table "notification"."alert" to "anon";

grant trigger on table "notification"."alert" to "anon";

grant truncate on table "notification"."alert" to "anon";

grant update on table "notification"."alert" to "anon";

grant delete on table "notification"."alert" to "authenticated";

grant insert on table "notification"."alert" to "authenticated";

grant references on table "notification"."alert" to "authenticated";

grant select on table "notification"."alert" to "authenticated";

grant trigger on table "notification"."alert" to "authenticated";

grant truncate on table "notification"."alert" to "authenticated";

grant update on table "notification"."alert" to "authenticated";

grant delete on table "notification"."alert" to "service_role";

grant insert on table "notification"."alert" to "service_role";

grant references on table "notification"."alert" to "service_role";

grant select on table "notification"."alert" to "service_role";

grant trigger on table "notification"."alert" to "service_role";

grant truncate on table "notification"."alert" to "service_role";

grant update on table "notification"."alert" to "service_role";

grant delete on table "notification"."alert_translation" to "anon";

grant insert on table "notification"."alert_translation" to "anon";

grant references on table "notification"."alert_translation" to "anon";

grant select on table "notification"."alert_translation" to "anon";

grant trigger on table "notification"."alert_translation" to "anon";

grant truncate on table "notification"."alert_translation" to "anon";

grant update on table "notification"."alert_translation" to "anon";

grant delete on table "notification"."alert_translation" to "authenticated";

grant insert on table "notification"."alert_translation" to "authenticated";

grant references on table "notification"."alert_translation" to "authenticated";

grant select on table "notification"."alert_translation" to "authenticated";

grant trigger on table "notification"."alert_translation" to "authenticated";

grant truncate on table "notification"."alert_translation" to "authenticated";

grant update on table "notification"."alert_translation" to "authenticated";

grant delete on table "notification"."alert_translation" to "service_role";

grant insert on table "notification"."alert_translation" to "service_role";

grant references on table "notification"."alert_translation" to "service_role";

grant select on table "notification"."alert_translation" to "service_role";

grant trigger on table "notification"."alert_translation" to "service_role";

grant truncate on table "notification"."alert_translation" to "service_role";

grant update on table "notification"."alert_translation" to "service_role";

grant delete on table "notification"."app_version" to "anon";

grant insert on table "notification"."app_version" to "anon";

grant references on table "notification"."app_version" to "anon";

grant select on table "notification"."app_version" to "anon";

grant trigger on table "notification"."app_version" to "anon";

grant truncate on table "notification"."app_version" to "anon";

grant update on table "notification"."app_version" to "anon";

grant delete on table "notification"."app_version" to "authenticated";

grant insert on table "notification"."app_version" to "authenticated";

grant references on table "notification"."app_version" to "authenticated";

grant select on table "notification"."app_version" to "authenticated";

grant trigger on table "notification"."app_version" to "authenticated";

grant truncate on table "notification"."app_version" to "authenticated";

grant update on table "notification"."app_version" to "authenticated";

grant delete on table "notification"."app_version" to "service_role";

grant insert on table "notification"."app_version" to "service_role";

grant references on table "notification"."app_version" to "service_role";

grant select on table "notification"."app_version" to "service_role";

grant trigger on table "notification"."app_version" to "service_role";

grant truncate on table "notification"."app_version" to "service_role";

grant update on table "notification"."app_version" to "service_role";

create policy "Enable delete for authenticated users only"
on "notification"."alert"
as permissive
for delete
to authenticated
using (true);


create policy "Enable insert for authenticated users only"
on "notification"."alert"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "notification"."alert"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "notification"."alert_translation"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "notification"."alert_translation"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "notification"."app_version"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "notification"."app_version"
as permissive
for select
to public
using (true);



create schema if not exists "player";

create sequence "player"."player_username_seq";

create table "player"."player" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "deleted_at" timestamp with time zone,
    "username" character varying,
    "is_guest" boolean not null default false,
    "user_id" uuid,
    "avatar_color" character varying
);


alter table "player"."player" enable row level security;

create table "player"."player_has_action_card" (
    "player_id" uuid not null,
    "room_id" integer not null,
    "action_card_id" smallint,
    "used_action_card_ids" smallint[],
    "last_player_id" uuid,
    "card_count" smallint
);


alter table "player"."player_has_action_card" enable row level security;

create table "player"."player_has_room" (
    "player_id" uuid not null,
    "room_id" integer not null,
    "joined_at" timestamp with time zone not null default now(),
    "last_seen" timestamp with time zone not null default now(),
    "paused" boolean not null default false
);


alter table "player"."player_has_room" enable row level security;

create table "player"."room" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "max_players" smallint not null default '15'::smallint,
    "name" character varying not null,
    "host_player_id" uuid not null,
    "in_game" boolean not null default false
);


alter table "player"."room" enable row level security;

create table "player"."room_event" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "room_id" integer not null,
    "event" character varying not null,
    "payload" jsonb not null
);


alter table "player"."room_event" enable row level security;

CREATE UNIQUE INDEX player_has_action_card_pkey ON player.player_has_action_card USING btree (room_id, player_id);

CREATE UNIQUE INDEX player_has_action_card_player_id_key ON player.player_has_action_card USING btree (player_id);

CREATE UNIQUE INDEX player_has_room_pkey ON player.player_has_room USING btree (player_id, room_id);

CREATE UNIQUE INDEX player_pkey ON player.player USING btree (id);

CREATE UNIQUE INDEX player_user_id_key ON player.player USING btree (user_id);

CREATE INDEX room_event_lookup_idx ON player.room_event USING btree (room_id, event, created_at DESC);

CREATE UNIQUE INDEX room_event_pkey ON player.room_event USING btree (id);

CREATE UNIQUE INDEX room_pkey ON player.room USING btree (id);

alter table "player"."player" add constraint "player_pkey" PRIMARY KEY using index "player_pkey";

alter table "player"."player_has_action_card" add constraint "player_has_action_card_pkey" PRIMARY KEY using index "player_has_action_card_pkey";

alter table "player"."player_has_room" add constraint "player_has_room_pkey" PRIMARY KEY using index "player_has_room_pkey";

alter table "player"."room" add constraint "room_pkey" PRIMARY KEY using index "room_pkey";

alter table "player"."room_event" add constraint "room_event_pkey" PRIMARY KEY using index "room_event_pkey";

alter table "player"."player" add constraint "player_player_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "player"."player" validate constraint "player_player_user_id_fkey";

alter table "player"."player" add constraint "player_user_id_key" UNIQUE using index "player_user_id_key";

alter table "player"."player_has_action_card" add constraint "player_has_action_card_player_id_key" UNIQUE using index "player_has_action_card_player_id_key";

alter table "player"."player_has_action_card" add constraint "player_player_has_action_card_room_id_fkey" FOREIGN KEY (room_id) REFERENCES player.room(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "player"."player_has_action_card" validate constraint "player_player_has_action_card_room_id_fkey";

alter table "player"."player_has_room" add constraint "player_player_has_room_player_id_fkey" FOREIGN KEY (player_id) REFERENCES player.player(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "player"."player_has_room" validate constraint "player_player_has_room_player_id_fkey";

alter table "player"."player_has_room" add constraint "player_player_has_room_room_id_fkey" FOREIGN KEY (room_id) REFERENCES player.room(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "player"."player_has_room" validate constraint "player_player_has_room_room_id_fkey";

alter table "player"."room" add constraint "player_room_host_player_id_fkey" FOREIGN KEY (host_player_id) REFERENCES player.player(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "player"."room" validate constraint "player_room_host_player_id_fkey";

alter table "player"."room_event" add constraint "room_event_room_id_fkey" FOREIGN KEY (room_id) REFERENCES player.room(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "player"."room_event" validate constraint "room_event_room_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION player.create_player_for_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into player.player (user_id)
  values (new.id);
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION player.delete_old_rooms()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
delete from player.room
where created_at < now() - interval '24 hours';
end;
$function$
;

CREATE OR REPLACE FUNCTION player.set_default_username()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
  -- Only set username if it's NULL
  IF NEW.username IS NULL AND NEW.is_guest = TRUE THEN
    NEW.username := 'User' || nextval('player.player_username_seq');
  END IF;
  RETURN NEW;
END;$function$
;

grant delete on table "player"."player" to "anon";

grant insert on table "player"."player" to "anon";

grant references on table "player"."player" to "anon";

grant select on table "player"."player" to "anon";

grant trigger on table "player"."player" to "anon";

grant truncate on table "player"."player" to "anon";

grant update on table "player"."player" to "anon";

grant delete on table "player"."player" to "authenticated";

grant insert on table "player"."player" to "authenticated";

grant references on table "player"."player" to "authenticated";

grant select on table "player"."player" to "authenticated";

grant trigger on table "player"."player" to "authenticated";

grant truncate on table "player"."player" to "authenticated";

grant update on table "player"."player" to "authenticated";

grant delete on table "player"."player" to "service_role";

grant insert on table "player"."player" to "service_role";

grant references on table "player"."player" to "service_role";

grant select on table "player"."player" to "service_role";

grant trigger on table "player"."player" to "service_role";

grant truncate on table "player"."player" to "service_role";

grant update on table "player"."player" to "service_role";

grant delete on table "player"."player_has_action_card" to "anon";

grant insert on table "player"."player_has_action_card" to "anon";

grant references on table "player"."player_has_action_card" to "anon";

grant select on table "player"."player_has_action_card" to "anon";

grant trigger on table "player"."player_has_action_card" to "anon";

grant truncate on table "player"."player_has_action_card" to "anon";

grant update on table "player"."player_has_action_card" to "anon";

grant delete on table "player"."player_has_action_card" to "authenticated";

grant insert on table "player"."player_has_action_card" to "authenticated";

grant references on table "player"."player_has_action_card" to "authenticated";

grant select on table "player"."player_has_action_card" to "authenticated";

grant trigger on table "player"."player_has_action_card" to "authenticated";

grant truncate on table "player"."player_has_action_card" to "authenticated";

grant update on table "player"."player_has_action_card" to "authenticated";

grant delete on table "player"."player_has_action_card" to "service_role";

grant insert on table "player"."player_has_action_card" to "service_role";

grant references on table "player"."player_has_action_card" to "service_role";

grant select on table "player"."player_has_action_card" to "service_role";

grant trigger on table "player"."player_has_action_card" to "service_role";

grant truncate on table "player"."player_has_action_card" to "service_role";

grant update on table "player"."player_has_action_card" to "service_role";

grant delete on table "player"."player_has_room" to "anon";

grant insert on table "player"."player_has_room" to "anon";

grant references on table "player"."player_has_room" to "anon";

grant select on table "player"."player_has_room" to "anon";

grant trigger on table "player"."player_has_room" to "anon";

grant truncate on table "player"."player_has_room" to "anon";

grant update on table "player"."player_has_room" to "anon";

grant delete on table "player"."player_has_room" to "authenticated";

grant insert on table "player"."player_has_room" to "authenticated";

grant references on table "player"."player_has_room" to "authenticated";

grant select on table "player"."player_has_room" to "authenticated";

grant trigger on table "player"."player_has_room" to "authenticated";

grant truncate on table "player"."player_has_room" to "authenticated";

grant update on table "player"."player_has_room" to "authenticated";

grant delete on table "player"."player_has_room" to "service_role";

grant insert on table "player"."player_has_room" to "service_role";

grant references on table "player"."player_has_room" to "service_role";

grant select on table "player"."player_has_room" to "service_role";

grant trigger on table "player"."player_has_room" to "service_role";

grant truncate on table "player"."player_has_room" to "service_role";

grant update on table "player"."player_has_room" to "service_role";

grant delete on table "player"."room" to "anon";

grant insert on table "player"."room" to "anon";

grant references on table "player"."room" to "anon";

grant select on table "player"."room" to "anon";

grant trigger on table "player"."room" to "anon";

grant truncate on table "player"."room" to "anon";

grant update on table "player"."room" to "anon";

grant delete on table "player"."room" to "authenticated";

grant insert on table "player"."room" to "authenticated";

grant references on table "player"."room" to "authenticated";

grant select on table "player"."room" to "authenticated";

grant trigger on table "player"."room" to "authenticated";

grant truncate on table "player"."room" to "authenticated";

grant update on table "player"."room" to "authenticated";

grant delete on table "player"."room" to "service_role";

grant insert on table "player"."room" to "service_role";

grant references on table "player"."room" to "service_role";

grant select on table "player"."room" to "service_role";

grant trigger on table "player"."room" to "service_role";

grant truncate on table "player"."room" to "service_role";

grant update on table "player"."room" to "service_role";

grant delete on table "player"."room_event" to "anon";

grant insert on table "player"."room_event" to "anon";

grant references on table "player"."room_event" to "anon";

grant select on table "player"."room_event" to "anon";

grant trigger on table "player"."room_event" to "anon";

grant truncate on table "player"."room_event" to "anon";

grant update on table "player"."room_event" to "anon";

grant delete on table "player"."room_event" to "authenticated";

grant insert on table "player"."room_event" to "authenticated";

grant references on table "player"."room_event" to "authenticated";

grant select on table "player"."room_event" to "authenticated";

grant trigger on table "player"."room_event" to "authenticated";

grant truncate on table "player"."room_event" to "authenticated";

grant update on table "player"."room_event" to "authenticated";

grant delete on table "player"."room_event" to "service_role";

grant insert on table "player"."room_event" to "service_role";

grant references on table "player"."room_event" to "service_role";

grant select on table "player"."room_event" to "service_role";

grant trigger on table "player"."room_event" to "service_role";

grant truncate on table "player"."room_event" to "service_role";

grant update on table "player"."room_event" to "service_role";

create policy "Enable delete access for all users"
on "player"."player"
as permissive
for delete
to public
using (true);


create policy "Enable insert access for all users"
on "player"."player"
as permissive
for insert
to public
with check (true);


create policy "Enable read access for all users"
on "player"."player"
as permissive
for select
to public
using (true);


create policy "Enable update access for all users"
on "player"."player"
as permissive
for update
to public
using (true)
with check (true);


create policy "Enable delete access for all users"
on "player"."player_has_action_card"
as permissive
for delete
to public
using (true);


create policy "Enable insert access for all users"
on "player"."player_has_action_card"
as permissive
for insert
to public
with check (true);


create policy "Enable read access for all users"
on "player"."player_has_action_card"
as permissive
for select
to public
using (true);


create policy "Enable update access for all users"
on "player"."player_has_action_card"
as permissive
for update
to public
using (true)
with check (true);


create policy "Enable delete access for all users"
on "player"."player_has_room"
as permissive
for delete
to public
using (true);


create policy "Enable insert access for all users"
on "player"."player_has_room"
as permissive
for insert
to public
with check (true);


create policy "Enable read access for all users"
on "player"."player_has_room"
as permissive
for select
to public
using (true);


create policy "Enable update access for all users"
on "player"."player_has_room"
as permissive
for update
to public
using (true)
with check (true);


create policy "Enable delete access for all users"
on "player"."room"
as permissive
for delete
to public
using (true);


create policy "Enable insert for authenticated users only"
on "player"."room"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "player"."room"
as permissive
for select
to public
using (true);


create policy "Enable update for authenticated users only"
on "player"."room"
as permissive
for update
to authenticated
using (true)
with check (true);


create policy "Enable insert access for all users"
on "player"."room_event"
as permissive
for insert
to public
with check (true);


create policy "Enable read access for all users"
on "player"."room_event"
as permissive
for select
to public
using (true);


CREATE TRIGGER trigger_set_username BEFORE INSERT ON player.player FOR EACH ROW EXECUTE FUNCTION player.set_default_username();


